on: [push]

name: CI

jobs:
  build_and_test:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Bikeshed
        run: pip3 install bikeshed && bikeshed update
      - name: Build docs
        run: make
