on: [push]

name: CI

jobs:
  build_and_test:
    name: Build Tech Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bikeshed
        run: pip3 install bikeshed && bikeshed update
      - name: Build docs
        run: aa-exec --profile=chrome make
